version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/db/migrations:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres@postgres:5432/taskmanager
      - CLIENT_URL=http://localhost:5173
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_SOCKET_URL=http://localhost:4000
    ports:
      - '5173:5173'
    depends_on:
      - server

volumes:
  postgres_data:
